// Code generated by mockery v2.43.2. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// DiscordServiceMock is an autogenerated mock type for the DiscordService type
type DiscordServiceMock struct {
	mock.Mock
}

type DiscordServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DiscordServiceMock) EXPECT() *DiscordServiceMock_Expecter {
	return &DiscordServiceMock_Expecter{mock: &_m.Mock}
}

// UpdateMessage provides a mock function with given fields: channelId, messageId, content
func (_m *DiscordServiceMock) UpdateMessage(channelId string, messageId string, content string) error {
	ret := _m.Called(channelId, messageId, content)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(channelId, messageId, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DiscordServiceMock_UpdateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMessage'
type DiscordServiceMock_UpdateMessage_Call struct {
	*mock.Call
}

// UpdateMessage is a helper method to define mock.On call
//   - channelId string
//   - messageId string
//   - content string
func (_e *DiscordServiceMock_Expecter) UpdateMessage(channelId interface{}, messageId interface{}, content interface{}) *DiscordServiceMock_UpdateMessage_Call {
	return &DiscordServiceMock_UpdateMessage_Call{Call: _e.mock.On("UpdateMessage", channelId, messageId, content)}
}

func (_c *DiscordServiceMock_UpdateMessage_Call) Run(run func(channelId string, messageId string, content string)) *DiscordServiceMock_UpdateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DiscordServiceMock_UpdateMessage_Call) Return(_a0 error) *DiscordServiceMock_UpdateMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DiscordServiceMock_UpdateMessage_Call) RunAndReturn(run func(string, string, string) error) *DiscordServiceMock_UpdateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewDiscordServiceMock creates a new instance of DiscordServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscordServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscordServiceMock {
	mock := &DiscordServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
