name: Build and Run

on:
  repository_dispatch:
    types: [pull_request]

env:
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  DISCORD_BOT_ID: ${{ vars.DISCORD_BOT_ID }}
  DISCORD_CHANNEL_ID: ${{ vars.DISCORD_CHANNEL_ID }}
  DISCORD_MESSAGE_ID: ${{ vars.DISCORD_MESSAGE_ID }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_ORG: ${{ vars.GH_ORGANIZATION }}
  TZ: Asia/Jakarta

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build
        run: go build -o bin/main cmd/main.go

      - name: Run
        run: ./bin/main '${{ toJson(github.event.client_payload) }}'
