name: Go

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Diff generated mocks
        run: |
          go run github.com/vektra/mockery/v2@v2.43.2
          git diff --exit-code HEAD

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
